#!/bin/bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
LC_ALL=C
HEX=(a b c d e f 0 1 2 3 4 5 6 7 8 9)
SL=0
while [ $SL -lt 17 ]
do
        num=`shuf -i 0-15 -n 1`
        RMAC="$RMAC""${HEX[$num]}"
        num=`shuf -i 0-15 -n 1`
        RMAC="$RMAC""${HEX[$num]}"
        SL=$[`echo $RMAC | wc -c` - 1]
    if [ $SL -lt 17 ]
            then
            RMAC=""$RMAC":"
    fi
done
echo $RMAC
exit 0
